
[package]
name = "ubl_did"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
bs58 = "0.5"
serde = { version = "1", features = ["derive"] }
ubl_receipt = { path = "../ubl_receipt" }
